Repository CSC207-2023Y-UofT/course-project-crazy-cards, pull requests merged in 2023-08, with the labels that each got.

#25 4 feature 4 play card feature
  src/main/java/controllers/PlayerGameController.java
  src/main/java/entities/ComputerPlayer.java
  src/main/java/entities/Game.java
  src/main/java/entities/Player.java
  src/main/java/use_cases/PlayerGameInputBoundary.java
  src/main/java/use_cases/PlayerGameInteractor.java
  src/main/java/use_cases/PlayerGameRequestModel.java
  src/main/java/use_cases/PlayerGameResponseModel.java
  src/test/java/entities/ComputerPlayerTest.java
  src/test/java/entities/GameTest.java
  src/test/java/use_cases/GameStateTest.java
  src/test/java/use_cases/PlayerGameInteractorTest.java
  src/test/java/use_cases/PlayerGameResponseModelTest.java
Labels: documentation, enhancement

#29 Update card values
  src/main/java/entities/Card.java
  src/main/java/entities/StandardDeck.java
  src/test/java/entities/GameTest.java
  src/test/java/use_cases/PlayerGameInteractorTest.java
  src/test/java/use_cases/PlayerGameResponseModelTest.java
Labels: enhancement

#22 Window management
  src/main/java/ui/components/NavigationButton.java
  src/main/java/ui/windows/CardLayoutManager.java
  src/main/java/ui/windows/ICardLayoutManager.java
  src/main/java/ui/windows/PaneDelegator.java
Labels: enhancement

#33 Add some window factories
  src/main/java/ui/factories/GameWindowFactory.java
  src/main/java/ui/factories/StatsWindowFactory.java
  src/main/java/ui/factories/WindowFactory.java
Labels: documentation, enhancement

#37 Fixing test cases
  src/test/java/entities/HumanPlayerTest.java
  src/test/java/tutorial/HelloWorldTest.java
Labels: enhancement

#38 Javadocs and formatting review
  src/main/java/controllers/PlayerGameController.java
  src/main/java/database/CSVDatabase.java
  src/main/java/database/DataAccess.java
  src/main/java/entities/Deck.java
  src/main/java/entities/Game.java
  src/main/java/entities/Hand.java
  src/main/java/entities/HumanPlayer.java
  src/main/java/entities/HumanPlayerFactory.java
  src/main/java/entities/ObservableGame.java
  src/main/java/entities/Player.java
  src/main/java/entities/StandardDeck.java
  src/main/java/ui/windows/StatsController.java
  src/main/java/ui/windows/StatsDelegator.java
  src/main/java/ui/windows/StatsDisplay.java
  src/main/java/ui/windows/StatsDisplayData.java
  src/main/java/ui/windows/StatsWindow.java
  src/main/java/ui/windows/Window.java
  src/main/java/use_cases/GameState.java
  src/main/java/use_cases/PlayerGameInputBoundary.java
  src/main/java/use_cases/PlayerGameInteractor.java
  src/main/java/use_cases/PlayerGameRequestModel.java
  src/main/java/use_cases/PlayerGameResponseModel.java
  src/main/java/usecases/PlayerInformation.java
Labels: documentation

#39 Better displays
  src/main/java/ui/windows/RulesDisplay.java
  src/main/java/ui/windows/StatsDisplay.java
Labels: enhancement

#40 6 feature 6 game creator
  src/main/java/controllers/GameCreationController.java
  src/main/java/controllers/PlayerCreationInformation.java
  src/main/java/database/CSVDatabase.java
  src/main/java/entities/HumanPlayerFactory.java
  src/main/java/ui/windows/RulesDisplay.java
  src/main/java/use_cases/DataAccess.java
  src/main/java/use_cases/GameCreationInputBoundary.java
  src/main/java/use_cases/GameCreationInteractor.java
  src/main/java/use_cases/GameCreationRequestModel.java
  src/main/java/use_cases/GameCreationResponseModel.java
  src/test/java/controllers/PlayerCreationInformationTest.java
  src/test/java/use_cases/GameCreationInteractorTest.java
  src/test/java/use_cases/GameCreationRequestModelTest.java
Labels: enhancement

#48 Enum refactor
  src/main/java/controllers/PlayerGameController.java
  src/main/java/entities/Card.java
  src/main/java/entities/Game.java
  src/main/java/entities/StandardDeck.java
  src/main/java/enums/Rank.java
  src/main/java/enums/Suit.java
  src/main/java/enums/TurnAction.java
  src/main/java/ui/components/DrawnCard.java
  src/main/java/ui/components/DrawnHand.java
  src/main/java/ui/windows/GameController.java
  src/main/java/ui/windows/GameDisplay.java
  src/main/java/use_cases/CardResponseModel.java
  src/main/java/use_cases/PlayerGameInteractor.java
  src/main/java/use_cases/PlayerGameRequestModel.java
  src/main/java/use_cases/PlayerGameResponseModel.java
  src/test/java/entities/CardTest.java
  src/test/java/entities/ComputerPlayerTest.java
  src/test/java/entities/GameTest.java
  src/test/java/entities/PlayerTest.java
  src/test/java/use_cases/PlayerGameInteractorTest.java
  src/test/java/use_cases/PlayerGameResponseModelTest.java
Labels: enhancement

#50 47 feature 18 game creation window
  src/main/java/controllers/GameCreationController.java
  src/main/java/ui/windows/CreationDisplay.java
  src/main/java/ui/windows/CreationWindow.java
Labels: enhancement

#49 36 misc 8 edit statistics UI
  src/main/java/controllers/PlayerGameController.java
  src/main/java/entities/Card.java
  src/main/java/ui/windows/StatsController.java
  src/main/java/ui/windows/StatsDelegator.java
  src/main/java/ui/windows/StatsDisplay.java
  src/main/java/ui/windows/StatsDisplayData.java
  src/main/java/use_cases/PlayerGameInteractor.java
Labels: enhancement

#55 [Feature 15] Java swing components for the cards
  src/main/java/ui/components/DrawnCard.java
  src/main/java/ui/components/DrawnHand.java
  src/main/java/ui/windows/GameDisplay.java
Labels: enhancement

#57 Main menu title
  src/main/java/ui/components/DrawnHand.java
  src/main/java/ui/windows/MenuDisplay.java
  src/main/java/ui/windows/StatsDisplay.java
Labels: bug

#59 56 feature 17 connect game creation to game play screen
  src/main/java/Main.java
  src/main/java/controllers/GameCreationController.java
  src/main/java/database/players.csv
  src/main/java/entities/Deck.java
  src/main/java/entities/Game.java
  src/main/java/entities/Player.java
  src/main/java/entities/StandardDeck.java
  src/main/java/enums/TurnAction.java
  src/main/java/ui/components/DrawnCard.java
  src/main/java/ui/components/DrawnHand.java
  src/main/java/ui/components/NavigationButton.java
  src/main/java/ui/factories/CreationWindowFactory.java
  src/main/java/ui/factories/GameWindowFactory.java
  src/main/java/ui/factories/MenuWindowFactory.java
  src/main/java/ui/factories/RuleWindowFactory.java
  src/main/java/ui/factories/StatsWindowFactory.java
  src/main/java/ui/windows/Window.java
  src/main/java/ui/windows/creation/CreationDisplay.java
  src/main/java/ui/windows/creation/CreationWindow.java
  src/main/java/ui/windows/game/CardDelegator.java
  src/main/java/ui/windows/game/CardDisplayData.java
  src/main/java/ui/windows/game/GameController.java
  src/main/java/ui/windows/game/GameDelegator.java
  src/main/java/ui/windows/game/GameDisplay.java
  src/main/java/ui/windows/game/GameDisplayData.java
  src/main/java/ui/windows/game/GameDrawDelegator.java
  src/main/java/ui/windows/game/GamePlayDelegator.java
  src/main/java/ui/windows/game/GameSkipDelegator.java
  src/main/java/ui/windows/game/GameWindow.java
  src/main/java/ui/windows/layout_managers/CardLayoutManager.java
  src/main/java/ui/windows/layout_managers/ICardLayoutManager.java
  src/main/java/ui/windows/layout_managers/PaneDelegator.java
  src/main/java/ui/windows/menu/MenuDisplay.java
  src/main/java/ui/windows/menu/MenuWindow.java
  src/main/java/ui/windows/rules/RulesDisplay.java
  src/main/java/ui/windows/rules/RulesWindow.java
  src/main/java/ui/windows/stats/StatsController.java
  src/main/java/ui/windows/stats/StatsDelegator.java
  src/main/java/ui/windows/stats/StatsDisplay.java
  src/main/java/ui/windows/stats/StatsDisplayData.java
  src/main/java/ui/windows/stats/StatsWindow.java
  src/main/java/use_cases/GameCreationInteractor.java
  src/main/java/use_cases/PlayerGameInteractor.java
  src/main/java/use_cases/PlayerGameRequestModel.java
  src/main/java/use_cases/PlayerGameResponseModel.java
  src/test/java/use_cases/GameCreationInteractorTest.java
  src/test/java/use_cases/PlayerGameInteractorTest.java
Labels: bug, enhancement

#62 Current card display
  src/main/java/ui/windows/game/GameDisplay.java
Labels: enhancement

#63 CA refactor
  src/main/java/controllers/CreationBridge.java
  src/main/java/controllers/GameBridge.java
  src/main/java/entities/CreationAccess.java
  src/main/java/entities/Game.java
  src/main/java/entities/GameAccess.java
  src/main/java/entities/GameManager.java
  src/main/java/entities/GameObserver.java
  src/main/java/entities/IObserverNotifier.java
  src/main/java/entities/ObservableGame.java
  src/main/java/entities/ObserverNotifier.java
  src/main/java/use_cases/GameCreationInteractor.java
  src/main/java/use_cases/GameState.java
  src/main/java/use_cases/PlayerGameInteractor.java
Labels: enhancement

#66 Fix entrypoint
  src/main/java/Main.java
  src/main/java/ui/factories/CreatorWindowFactory.java
  src/main/java/ui/factories/GameWindowFactory.java
  src/main/java/ui/factories/StatsWindowFactory.java
  src/main/java/ui/windows/creation/CreationDisplay.java
  src/main/java/ui/windows/creation/CreationWindow.java
  src/main/java/ui/windows/game/GameController.java
  src/main/java/ui/windows/stats/StatsController.java
Labels: enhancement

#73 Fix entrypoint
  src/main/java/Main.java
  src/main/java/controllers/GameCreationController.java
  src/main/java/ui/components/PriorityActionListener.java
  src/main/java/ui/factories/CreationWindowFactory.java
  src/main/java/ui/factories/CreatorWindowFactory.java
  src/main/java/ui/factories/GameWindowFactory.java
  src/main/java/ui/windows/SwapEvent.java
  src/main/java/ui/windows/SwapListener.java
  src/main/java/ui/windows/creator/CreatorDisplay.java
  src/main/java/ui/windows/creator/CreatorWindow.java
  src/main/java/ui/windows/game/GameController.java
  src/main/java/ui/windows/game/GameDisplay.java
  src/main/java/ui/windows/game/GameDrawDelegator.java
  src/main/java/ui/windows/game/GamePlayDelegator.java
  src/main/java/ui/windows/game/GameSkipDelegator.java
  src/main/java/ui/windows/game/GameWindow.java
  src/main/java/ui/windows/game/SwitchUpdater.java
  src/main/java/ui/windows/layout_managers/CardLayoutManager.java
  src/main/java/use_cases/GameState.java
  src/main/java/use_cases/PlayerGameInteractor.java
Labels: bug, enhancement

#70 How to play page
  src/main/java/Main.java
  src/main/java/enums/WindowName.java
  src/main/java/ui/factories/HowtoWindowFactory.java
  src/main/java/ui/windows/howto/HowtoDisplay.java
  src/main/java/ui/windows/howto/HowtoWindow.java
  src/main/java/ui/windows/menu/MenuDisplay.java
  src/main/java/ui/windows/rules/RulesDisplay.java
Labels: enhancement

#68 Players and card display table
  src/main/java/ui/components/DrawnHand.java
  src/main/java/ui/windows/creator/CreatorDisplay.java
  src/main/java/ui/windows/game/GameController.java
  src/main/java/ui/windows/game/GameDisplay.java
  src/main/java/ui/windows/game/GameDisplayData.java
  src/main/java/use_cases/PlayerGameResponseModel.java
Labels: enhancement

#72 Updated DataAccess to save wins and losses automatically after a Game ends.
  src/main/java/Main.java
  src/main/java/database/CSVDatabase.java
  src/main/java/use_cases/DataAccess.java
Labels: enhancement

#75 Update main class
  src/main/java/Main.java
  src/main/java/ui/windows/menu/MenuDisplay.java
Labels: bug, enhancement

#76 More documentation
  src/main/java/Main.java
  src/main/java/entities/GameManager.java
  src/main/java/entities/IObserverNotifier.java
  src/main/java/entities/ObserverNotifier.java
  src/main/java/enums/TurnAction.java
  src/main/java/enums/WindowName.java
  src/main/java/ui/components/DrawnHand.java
  src/main/java/ui/factories/CreatorWindowFactory.java
  src/main/java/ui/factories/GameWindowFactory.java
  src/main/java/ui/factories/MenuWindowFactory.java
  src/main/java/ui/factories/RuleWindowFactory.java
  src/main/java/ui/windows/Window.java
  src/main/java/ui/windows/creator/CreatorDisplay.java
  src/main/java/ui/windows/creator/CreatorWindow.java
  src/main/java/ui/windows/game/CardDisplayData.java
  src/main/java/ui/windows/game/GameDisplay.java
  src/main/java/ui/windows/game/GameDrawDelegator.java
  src/main/java/ui/windows/game/GamePlayDelegator.java
  src/main/java/ui/windows/game/GameSkipDelegator.java
  src/main/java/ui/windows/game/GameWindow.java
  src/main/java/ui/windows/howto/HowtoDisplay.java
  src/main/java/ui/windows/layout_managers/CardLayoutManager.java
  src/main/java/ui/windows/menu/MenuWindow.java
  src/main/java/ui/windows/rules/RulesWindow.java
  src/main/java/ui/windows/stats/StatsController.java
  src/main/java/ui/windows/stats/StatsDelegator.java
  src/main/java/ui/windows/stats/StatsDisplay.java
  src/main/java/ui/windows/stats/StatsDisplayData.java
  src/main/java/ui/windows/stats/StatsWindow.java
  src/main/java/use_cases/CardResponseModel.java
  src/main/java/use_cases/DataAccess.java
  src/main/java/use_cases/GameCreationInteractor.java
  src/main/java/use_cases/GameCreationResponseModel.java
  src/main/java/use_cases/GameState.java
Labels: documentation

#77 65 feature 21 give option to go back to menu when game is won
  src/main/java/Main.java
  src/main/java/ui/windows/game/GameController.java
  src/main/java/ui/windows/game/GameDisplay.java
  src/main/java/ui/windows/game/GameDisplayData.java
  src/main/java/ui/windows/game/GameWindow.java
  src/main/java/use_cases/PlayerGameInteractor.java
Labels: documentation, enhancement

#81 Card effects
  src/main/java/entities/Card.java
  src/main/java/entities/CustomDeck.java
  src/main/java/entities/DeckGenerationParameters.java
  src/main/java/entities/EffectGenerationParameters.java
  src/main/java/entities/ForceDrawEffect.java
  src/main/java/entities/Game.java
  src/main/java/entities/GameAccess.java
  src/main/java/entities/GameManager.java
  src/main/java/entities/Player.java
  src/main/java/entities/RandomRankEffect.java
  src/main/java/entities/RandomSuitEffect.java
  src/main/java/entities/ReverseEffect.java
  src/main/java/entities/SkipTurnEffect.java
  src/main/java/entities/SpecialEffect.java
  src/main/java/entities/StandardDeck.java
  src/main/java/use_cases/PlayerGameInteractor.java
Labels: enhancement

#80 79 misc 14 bug fixing for database and gamecontroller
  build.gradle
  src/main/java/controllers/GameCreationController.java
  src/main/java/database/CSVDatabase.java
  src/main/java/database/players.csv
  src/main/java/ui/windows/game/GameController.java
  src/main/java/use_cases/PlayerGameInteractor.java
Labels: bug, enhancement

#89 52 misc 10 update tests
  src/main/java/Main.java
  src/main/java/database/CSVDatabase.java
  src/main/java/entities/card_logic/Card.java
  src/main/java/entities/card_logic/EffectGenerationParameters.java
  src/main/java/entities/card_logic/ForceDrawEffect.java
  src/main/java/entities/card_logic/RandomRankEffect.java
  src/main/java/entities/card_logic/RandomSuitEffect.java
  src/main/java/entities/card_logic/ReverseEffect.java
  src/main/java/entities/card_logic/SkipTurnEffect.java
  src/main/java/entities/card_logic/SpecialEffect.java
  src/main/java/entities/deck_logic/CustomDeck.java
  src/main/java/entities/deck_logic/Deck.java
  src/main/java/entities/deck_logic/DeckGenerationParameters.java
  src/main/java/entities/deck_logic/StandardDeck.java
  src/main/java/entities/game_logic/CreationAccess.java
  src/main/java/entities/game_logic/Game.java
  src/main/java/entities/game_logic/GameAccess.java
  src/main/java/entities/game_logic/GameManager.java
  src/main/java/entities/game_logic/GameObserver.java
  src/main/java/entities/game_logic/IObserverNotifier.java
  src/main/java/entities/game_logic/ObservableGame.java
  src/main/java/entities/game_logic/ObserverNotifier.java
  src/main/java/entities/player_logic/ComputerPlayer.java
  src/main/java/entities/player_logic/ComputerPlayerFactory.java
  src/main/java/entities/player_logic/ConcretePlayer.java
  src/main/java/entities/player_logic/Hand.java
  src/main/java/entities/player_logic/HumanPlayer.java
  src/main/java/entities/player_logic/HumanPlayerFactory.java
  src/main/java/entities/player_logic/Player.java
  src/main/java/entities/player_logic/PlayerFactory.java
  src/main/java/use_cases/DataAccess.java
  src/main/java/use_cases/GameCreationInteractor.java
  src/main/java/use_cases/GameState.java
  src/main/java/use_cases/PlayerGameInteractor.java
  src/main/java/use_cases/PlayerGameResponseModel.java
  src/test/java/database/SaveLoadPlayerTest.java
  src/test/java/entities/CardTest.java
  src/test/java/entities/ComputerPlayerTest.java
  src/test/java/entities/GameTest.java
  src/test/java/entities/HandTest.java
  src/test/java/entities/HumanPlayerTest.java
  src/test/java/entities/PlayerTest.java
  src/test/java/entities/StandardDeckTest.java
  src/test/java/use_cases/GameCreationInteractorTest.java
  src/test/java/use_cases/GameStateTest.java
  src/test/java/use_cases/PlayerGameInteractorTest.java
  src/test/java/use_cases/PlayerGameResponseModelTest.java
Labels: bug, enhancement

#91 90 misc 18 get tests to pass
  src/main/java/entities/game_logic/Game.java
  src/test/java/controllers/GameCreationControllerTest.java
  src/test/java/database/SaveLoadPlayerTest.java
  src/test/java/entities/CardTest.java
  src/test/java/entities/GameTest.java
  src/test/java/entities/HandTest.java
  src/test/java/entities/HumanPlayerTest.java
  src/test/java/entities/PlayerTest.java
  src/test/java/entities/StandardDeckTest.java
  src/test/java/ui/components/PriorityActionListenerTest.java
  src/test/java/use_cases/GameCreationInteractorTest.java
  src/test/java/use_cases/GameCreationRequestModelTest.java
  src/test/java/use_cases/GameStateTest.java
  src/test/java/use_cases/PlayerGameInteractorTest.java
  src/test/java/use_cases/PlayerGameResponseModelTest.java
Labels: bug, enhancement

#94 Fix tests
  src/test/java/controllers/GameCreationControllerTest.java
Labels: bug

#95 UI updates
  src/main/java/Main.java
  src/main/java/controllers/GameController.java
  src/main/java/controllers/data_objects/GameDisplayData.java
  src/main/java/entities/game_logic/Game.java
  src/main/java/entities/game_logic/GameAccess.java
  src/main/java/entities/game_logic/GameManager.java
  src/main/java/ui/components/DrawnCard.java
  src/main/java/ui/components/DrawnHand.java
  src/main/java/ui/windows/game/CardDelegator.java
  src/main/java/ui/windows/game/GameDisplay.java
  src/main/java/ui/windows/howto/HowtoDisplay.java
  src/main/java/ui/windows/rules/RulesDisplay.java
  src/main/java/use_cases/GameState.java
  src/main/java/use_cases/PlayerGameInteractor.java
  src/main/java/use_cases/PlayerGameResponseModel.java
Labels: enhancement
